curl -X POST https://ubvo4sq5ak.execute-api.us-east-1.amazonaws.com/dev/appointment
-h 'Content-Type: application/json'
-d '{
    "name": "Juan",
    "age": 30,
    "medicId": 3,
    "centerId": 34,
    "specialtyId": 1,
    "subSpecialtyId": 23,
    "dateAppointment": "2023-10-02T14:00:00.000Z",
    "countryISO": "PE"
}'
